"$schema" = 'https://starship.rs/config-schema.json'

# Todo: Convert this to a j2 template to make switching themes better
# Todo: Only load Python module if venv is sourced

# Configures the format of the prompt.
format = """
[](os_bg)$os$username[]\
(bg:dir_bg fg:os_bg)\
$directory[]\
(fg:dir_bg bg:git_bg)\
$git_branch$git_status[]\
(fg:git_bg bg:lang_bg)\
$c$rust$golang$python[]\
(fg:lang_bg bg:red)\
$cmd_duration[ ](red)\
$fill\
([ ](os_bg)$time$battery[](fg:os_bg))\
$line_break$character"""

# Sets the palette to "one_dark".
palette = 'carbonfox'

# Sets the colors of the "one_dark" palette.
[palettes.carbonfox]
red = "#ee5396"
green = "#25be6a"
purple = "#be95ff"
yellow = "#08bdba"
os_bg = "#7b7c7e"
os_fg = "#0c0c0c"
dir_bg = "#25be6a"
dir_fg = "#161616"
git_bg = "#08bdba"
git_fg = "#252525"
lang_bg = "#78a9ff"
lang_fg = "#353535"

# Module that displays the current OS.
[os]
disabled = false # Disabled by default
style = "bg:os_bg fg:os_fg"
format = '[ $symbol ]($style)'

# Sets custom symbols for each OS.
[os.symbols]
Alpine = ""
Amazon = ""
Android = "󰀲"
Arch = ""
CentOS = ""
Debian = "󰣚"
Fedora = "󰣛"
FreeBSD = "󰣠"
Gentoo = "󰣨"
Linux = "󰌽"
Macos = "󰀵"
Manjaro = "󱘊"
Mint = "󰣭"
NixOS = "󱄅"
OpenBSD = ""
openSUSE = ""
Pop = ""
Raspbian = ""
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
SUSE = ""
Ubuntu = "󰕈"
Unknown = ""
Windows = "󰍲"

# Module that displays the current username.
[username]
show_always = true
style_user = "bg:os_bg fg:os_fg"
style_root = "bg:os_bg fg:os_fg"
format = '[ $user ]($style)'

# Module that displays the current directory.
[directory]
style = "fg:dir_fg bg:dir_bg"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Sets the custom symbols for directories.
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "

# Module that displays the current git branch.
[git_branch]
symbol = ""
style = "bg:git_bg"
format = '[[ $symbol $branch ](fg:git_fg bg:git_bg)]($style)'

# Module that displays the current git status.
[git_status]
disabled =true
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
style = "bg:git_bg"
format = '[[($all_status$ahead_behind )](fg:git_fg bg:git_bg)]($style)'

# Language specific modules
[nodejs]
symbol = ""
style = "bg:lang_bg"
format = '[[ $symbol( $version) ](fg:lang_fg bg:lang_bg)]($style)'

[c]
symbol = " "
style = "bg:lang_bg"
format = '[[ $symbol( $version) ](fg:lang_fg bg:lang_bg)]($style)'

[dotnet]
symbol = "󰪮"
style = "bg:lang_bg"
format = '[[ $symbol( $version) ](fg:lang_fg bg:lang_bg)]($style)'

[rust]
symbol = ""
style = "bg:lang_bg"
format = '[[ $symbol( $version) ](fg:lang_fg bg:lang_bg)]($style)'

[golang]
symbol = ""
style = "bg:lang_bg"
format = '[[ $symbol( $version) ](fg:lang_fg bg:lang_bg)]($style)'

[php]
symbol = " "
style = "bg:lang_bg"
format = '[[ $symbol( $version) ](fg:lang_fg bg:lang_bg)]($style)'

[java]
symbol = " "
style = "bg:lang_bg"
format = '[[ $symbol( $version) ](fg:lang_fg bg:lang_bg)]($style)'

[kotlin]
symbol = " "
style = "bg:lang_bg"
format = '[[ $symbol( $version) ](fg:lang_fg bg:lang_bg)]($style)'

[haskell]
symbol = " "
style = "bg:lang_bg"
format = '[[ $symbol( $version) ](fg:lang_fg bg:lang_bg)]($style)'

[python]
symbol = " "
style = "bg:lang_bg"
format = '[[ $symbol( $version) ](fg:lang_fg bg:lang_bg)]($style)'

[elixir]
symbol = " "
style = "bg:lang_bg"
format = '[[ $symbol( $version) ](fg:lang_fg bg:lang_bg)]($style)'

[elm]
symbol = " "
style = "bg:lang_bg"
format = '[[ $symbol( $version) ](fg:lang_fg bg:lang_bg)]($style)'

[gradle]
symbol = " "
style = "bg:lang_bg"
format = '[[ $symbol( $version) ](fg:lang_fg bg:lang_bg)]($style)'

[julia]
symbol = " "
style = "bg:lang_bg"
format = '[[ $symbol( $version) ](fg:lang_fg bg:lang_bg)]($style)'

[nim]
symbol = "󰆥 "
style = "bg:lang_bg"
format = '[[ $symbol( $version) ](fg:lang_fg bg:lang_bg)]($style)'

[scala]
symbol = " "
style = "bg:lang_bg"
format = '[[ $symbol( $version) ](fg:lang_fg bg:lang_bg)]($style)'

[cmd_duration]
format = '[[ 󱦟 $duration ](bg:red)]($style)'
#Note: Can't display duration in ms only, prints like 2s11ms :/
show_milliseconds = true

# Module that fills the space between the left and right segments.
[fill]
symbol = " "

# Module that displays the time.
[time]
disabled = false # Disabled by default
use_12hr = false # Disable for 24h format without seconds
format = '[[ 󰥔 $time ](fg:os_fg bg:os_bg)]($style)'

# Module that displays the battery level and status.
[battery]
format = '[$symbol $percentage ]($style)'

# Battery symbols and colors for each threshold.
[[battery.display]]
threshold = 10
style = "bold bg:os_bg fg:red"
discharging_symbol = "󰁺"
charging_symbol = "󰢜"

[[battery.display]]
threshold = 20
style = "bold bg:os_bg fg:red"
discharging_symbol = "󰁻"
charging_symbol = "󰂆"

[[battery.display]]
threshold = 30
style = "bold bg:os_bg fg:yellow"
discharging_symbol = "󰁼"
charging_symbol = "󰂇"

[[battery.display]]
threshold = 40
style = "bold bg:os_bg fg:yellow"
discharging_symbol = "󰁽"
charging_symbol = "󰂈"

[[battery.display]]
threshold = 50
style = "bold bg:os_bg fg:yellow"
discharging_symbol = "󰁾"
charging_symbol = "󰢝"

[[battery.display]]
threshold = 60
style = "bold bg:os_bg fg:green"
discharging_symbol = "󰁿"
charging_symbol = "󰂉"

[[battery.display]]
threshold = 70
style = "bold bg:os_bg fg:green"
discharging_symbol = "󰂀"
charging_symbol = "󰢞"

[[battery.display]]
threshold = 80
style = "bold bg:os_bg fg:green"
discharging_symbol = "󰂁"
charging_symbol = "󰂊"

[[battery.display]]
threshold = 90
style = "bold bg:os_bg fg:green"
discharging_symbol = "󰂂"
charging_symbol = "󰂋"

[[battery.display]]
style = "bold bg:os_bg fg:green"
discharging_symbol = "󰁹"
charging_symbol = "󰂅"
threshold = 100

# New line character
[character]
success_symbol = '[❯](bold fg:#25be6a)'
error_symbol = '[](bold fg:#ee5396)'
vimcmd_symbol = '[󰅁](bold fg:green)'
vimcmd_replace_one_symbol = '[󰅁](bold fg:purple)'
vimcmd_replace_symbol = '[󰅁](bold fg:purple)'
vimcmd_visual_symbol = '[󰅁](bold fg:yellow)'
