# Character set to use (see Character Sets section)
char_set = "default"

# Theme to use (see Themes section)
theme = "default"

# Initial tab
tab = "output"

# Name Overrides
#
# Name overrides define alternate templates that will be used for objects
# matching a given criterion.
#
# An override is matched by type, which contains a list of one or more of
# stream, endpoint, or device (see the Name section for more details), and a
# property value. Any node or device property that can be used in the names
# section can be used to match an override.
#
# There are no default overrides, but here is an example. This causes all
# streams whose node.name is "spotify" to use just "{node:node.name}" as its
# name.
#
# [[names.overrides]]
# # Which object types this override applies to
# types = [ "stream" ]
# # The property to match
# property = "node:node.name"
# # The value to match
# value = "spotify"
# # Templates to use when the property value matches
# templates = [ "{node:node.name}" ]
#
# You can have multiple name overrides, each in its own [[names.overrides]]
# section.
