# Note: No ligature support sucks
[general]
import = ["./onedarkpro-onedark.toml"]

[window]
# Note: Buttonless is slightly better than None as you get rounded windows
# "Full" | "None" | "Transparent" | "Buttonless"
decorations="Buttonless"
option_as_alt="Both"
padding = { x = 0, y = 0 }
dynamic_padding = true

[scrolling]
history=100000

[font]
size = 18

[font.normal]
family = "Maple Mono"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

# Note: man alacritty-bindings for default bindings
# ctl + shift + space -> enter VI mode
